// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bjpfQjX9aYZ_KpZCnZ3z-hPNkp630E8',
    appId: '1:54539222544:web:291b9aed233ed3b87b1495',
    messagingSenderId: '54539222544',
    projectId: 'lacos-be754',
    authDomain: 'lacos-be754.firebaseapp.com',
    storageBucket: 'lacos-be754.firebasestorage.app',
    measurementId: 'G-TN36P2BQGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6tcbUU3wVdFsrs1yVFT3o3p-kJhNFqg',
    appId: '1:54539222544:android:fe21a6fb3540edb07b1495',
    messagingSenderId: '54539222544',
    projectId: 'lacos-be754',
    storageBucket: 'lacos-be754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUW3e8iPxJ3rhZlGV0hulaZW2DklZ41w',
    appId: '1:54539222544:ios:a967bd471d7023827b1495',
    messagingSenderId: '54539222544',
    projectId: 'lacos-be754',
    storageBucket: 'lacos-be754.firebasestorage.app',
    iosBundleId: 'com.example.lacos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUW3e8iPxJ3rhZlGV0hulaZW2DklZ41w',
    appId: '1:54539222544:ios:a967bd471d7023827b1495',
    messagingSenderId: '54539222544',
    projectId: 'lacos-be754',
    storageBucket: 'lacos-be754.firebasestorage.app',
    iosBundleId: 'com.example.lacos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0bjpfQjX9aYZ_KpZCnZ3z-hPNkp630E8',
    appId: '1:54539222544:web:d67b3ef9dd044f3a7b1495',
    messagingSenderId: '54539222544',
    projectId: 'lacos-be754',
    authDomain: 'lacos-be754.firebaseapp.com',
    storageBucket: 'lacos-be754.firebasestorage.app',
    measurementId: 'G-BDXLG78MPH',
  );
}
