#!/bin/bash

# Script para configurar Android SDK para desenvolvimento

echo "🔧 Configurando Android SDK..."
echo ""

# Verificar se ANDROID_HOME está configurado
if [ -z "$ANDROID_HOME" ]; then
    echo "⚠️  ANDROID_HOME não está configurado"
    echo "📝 Configurando ANDROID_HOME..."
    export ANDROID_HOME=/usr/lib/android-sdk
    export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
    
    # Adicionar ao .bashrc se não existir
    if ! grep -q "ANDROID_HOME" ~/.bashrc 2>/dev/null; then
        cat >> ~/.bashrc << 'EOF'

# Android SDK Configuration
export ANDROID_HOME=/usr/lib/android-sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
EOF
        echo "✅ ANDROID_HOME adicionado ao ~/.bashrc"
    fi
else
    echo "✅ ANDROID_HOME já está configurado: $ANDROID_HOME"
fi

# Verificar se local.properties existe
if [ ! -f "android/local.properties" ]; then
    echo "📝 Criando android/local.properties..."
    mkdir -p android
    cat > android/local.properties << EOF
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
sdk.dir=$ANDROID_HOME
EOF
    echo "✅ android/local.properties criado"
else
    echo "✅ android/local.properties já existe"
fi

# Verificar componentes do SDK
echo ""
echo "🔍 Verificando componentes do Android SDK..."
echo ""

if [ ! -d "$ANDROID_HOME/platforms" ]; then
    echo "⚠️  Diretório 'platforms' não encontrado"
    echo "   O SDK pode estar incompleto. Você pode precisar instalar:"
    echo "   - Android SDK Platform (API 33 ou superior)"
    echo "   - Android SDK Build-Tools"
    echo ""
    echo "   Opções:"
    echo "   1. Instalar Android Studio e usar o SDK Manager"
    echo "   2. Usar o comando sdkmanager (se disponível)"
    echo "   3. O Expo pode baixar automaticamente durante o build"
fi

if [ ! -d "$ANDROID_HOME/build-tools" ]; then
    echo "⚠️  Diretório 'build-tools' não encontrado"
fi

# Verificar dispositivos conectados
echo ""
echo "📱 Verificando dispositivos Android..."
echo ""
adb devices

echo ""
echo "✅ Configuração concluída!"
echo ""
echo "📝 Para usar em uma nova sessão de terminal, execute:"
echo "   source ~/.bashrc"
echo ""
echo "💡 Dica: Se você não tem um dispositivo físico conectado,"
echo "   você pode usar o Expo Go app ou criar um emulador."
