<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = array (
  0 => 
  array (
    'id' => 1,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Losartana',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 01:53:46',
    'updated_at' => '2026-01-25 01:53:46',
    'deleted_at' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Losartana',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => 'Verb',
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 01:55:31',
    'updated_at' => '2026-01-25 01:55:31',
    'deleted_at' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Atorvastatina',
    'pharmaceutical_form' => NULL,
    'dosage' => '20',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 02:02:25',
    'updated_at' => '2026-01-25 02:02:25',
    'deleted_at' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Beclometasona',
    'pharmaceutical_form' => NULL,
    'dosage' => '40',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 02:02:59',
    'updated_at' => '2026-01-25 02:02:59',
    'deleted_at' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Sinvastatina',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => 'BB',
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 02:14:23',
    'updated_at' => '2026-01-25 02:14:23',
    'deleted_at' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Citalopram',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 03:51:03',
    'updated_at' => '2026-01-25 03:51:03',
    'deleted_at' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Cetoprofeno',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:30:29',
    'updated_at' => '2026-01-25 04:30:29',
    'deleted_at' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Loratadina',
    'pharmaceutical_form' => NULL,
    'dosage' => '20',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:31:13',
    'updated_at' => '2026-01-25 04:31:13',
    'deleted_at' => NULL,
  ),
  8 => 
  array (
    'id' => 9,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Benzetacil',
    'pharmaceutical_form' => NULL,
    'dosage' => '50',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:32:42',
    'updated_at' => '2026-01-25 04:32:42',
    'deleted_at' => NULL,
  ),
  9 => 
  array (
    'id' => 10,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Tramadol',
    'pharmaceutical_form' => NULL,
    'dosage' => '80',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:33:32',
    'updated_at' => '2026-01-25 04:33:32',
    'deleted_at' => NULL,
  ),
  10 => 
  array (
    'id' => 11,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Insulina NPH',
    'pharmaceutical_form' => NULL,
    'dosage' => '80',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:34:30',
    'updated_at' => '2026-01-25 04:34:30',
    'deleted_at' => NULL,
  ),
  11 => 
  array (
    'id' => 12,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Dipirona',
    'pharmaceutical_form' => NULL,
    'dosage' => '10',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:35:26',
    'updated_at' => '2026-01-25 04:35:26',
    'deleted_at' => NULL,
  ),
  12 => 
  array (
    'id' => 13,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Enalapril',
    'pharmaceutical_form' => NULL,
    'dosage' => '12',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => 'Hvvv',
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:38:46',
    'updated_at' => '2026-01-25 04:38:46',
    'deleted_at' => NULL,
  ),
  13 => 
  array (
    'id' => 14,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Sertralina',
    'pharmaceutical_form' => NULL,
    'dosage' => '70',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 04:56:31',
    'updated_at' => '2026-01-25 04:56:31',
    'deleted_at' => NULL,
  ),
  14 => 
  array (
    'id' => 15,
    'accompanied_person_id' => 1,
    'group_id' => 1,
    'prescription_id' => NULL,
    'name' => 'Amoxicilina',
    'pharmaceutical_form' => NULL,
    'dosage' => '20',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 05:01:05',
    'updated_at' => '2026-01-25 05:01:05',
    'deleted_at' => NULL,
  ),
  15 => 
  array (
    'id' => 16,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Dipirona Sódica',
    'pharmaceutical_form' => NULL,
    'dosage' => '500',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"6","schedule":["19:00","01:00","07:00","13:00"]}}',
    'time' => '19:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-25 23:09:09',
    'updated_at' => '2026-01-25 23:09:09',
    'deleted_at' => NULL,
  ),
  16 => 
  array (
    'id' => 17,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Losartana',
    'pharmaceutical_form' => 'Gotas',
    'dosage' => '500',
    'dose_quantity' => '12',
    'dose_quantity_unit' => 'gota(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 01:39:26',
    'updated_at' => '2026-01-26 01:39:26',
    'deleted_at' => NULL,
  ),
  17 => 
  array (
    'id' => 18,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Atenolol',
    'pharmaceutical_form' => 'Gotas',
    'dosage' => '500',
    'dose_quantity' => '12',
    'dose_quantity_unit' => 'gota(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 01:43:59',
    'updated_at' => '2026-01-26 01:43:59',
    'deleted_at' => NULL,
  ),
  18 => 
  array (
    'id' => 20,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Citalopram',
    'pharmaceutical_form' => 'Gotas',
    'dosage' => '740',
    'dose_quantity' => '14',
    'dose_quantity_unit' => 'gota(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 01:58:25',
    'updated_at' => '2026-01-26 02:05:49',
    'deleted_at' => NULL,
  ),
  19 => 
  array (
    'id' => 23,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Beclometasona',
    'pharmaceutical_form' => NULL,
    'dosage' => '500',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:01:23',
    'updated_at' => '2026-01-26 02:05:49',
    'deleted_at' => NULL,
  ),
  20 => 
  array (
    'id' => 24,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => NULL,
    'name' => 'Amoxicilina',
    'pharmaceutical_form' => NULL,
    'dosage' => '222',
    'dose_quantity' => NULL,
    'dose_quantity_unit' => NULL,
    'unit' => NULL,
    'administration_route' => NULL,
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:01:23',
    'updated_at' => '2026-01-26 02:05:49',
    'deleted_at' => NULL,
  ),
  21 => 
  array (
    'id' => 36,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 7,
    'name' => 'Losartana',
    'pharmaceutical_form' => 'Cápsula',
    'dosage' => '58',
    'dose_quantity' => '12',
    'dose_quantity_unit' => 'cápsula(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:17:31',
    'updated_at' => '2026-01-26 02:17:31',
    'deleted_at' => NULL,
  ),
  22 => 
  array (
    'id' => 37,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 7,
    'name' => 'Tramadol',
    'pharmaceutical_form' => 'Cápsula',
    'dosage' => '123',
    'dose_quantity' => '25',
    'dose_quantity_unit' => 'cápsula(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:17:31',
    'updated_at' => '2026-01-26 02:17:31',
    'deleted_at' => NULL,
  ),
  23 => 
  array (
    'id' => 38,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 7,
    'name' => 'Loratadina',
    'pharmaceutical_form' => 'Cápsula',
    'dosage' => '500',
    'dose_quantity' => '60',
    'dose_quantity_unit' => 'cápsula(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:17:31',
    'updated_at' => '2026-01-26 02:17:31',
    'deleted_at' => NULL,
  ),
  24 => 
  array (
    'id' => 39,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 8,
    'name' => 'Tramadol',
    'pharmaceutical_form' => 'Cápsula',
    'dosage' => '600',
    'dose_quantity' => '12',
    'dose_quantity_unit' => 'cápsula(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:28:27',
    'updated_at' => '2026-01-26 02:28:27',
    'deleted_at' => NULL,
  ),
  25 => 
  array (
    'id' => 40,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 9,
    'name' => 'Famotidina',
    'pharmaceutical_form' => 'Sachê',
    'dosage' => '580',
    'dose_quantity' => '25',
    'dose_quantity_unit' => 'sachê',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:33:38',
    'updated_at' => '2026-01-26 02:33:38',
    'deleted_at' => NULL,
  ),
  26 => 
  array (
    'id' => 41,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 9,
    'name' => 'Amoxicilina',
    'pharmaceutical_form' => 'Solução',
    'dosage' => '800',
    'dose_quantity' => '12',
    'dose_quantity_unit' => 'mL',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-01-25',
    'end_date' => NULL,
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-01-26 02:33:38',
    'updated_at' => '2026-01-26 02:33:38',
    'deleted_at' => NULL,
  ),
  27 => 
  array (
    'id' => 42,
    'accompanied_person_id' => 2,
    'group_id' => 2,
    'prescription_id' => 10,
    'name' => 'Losartana',
    'pharmaceutical_form' => 'Comprimido',
    'dosage' => '20',
    'dose_quantity' => '8',
    'dose_quantity_unit' => 'comprimido(s)',
    'unit' => 'mg',
    'administration_route' => 'Oral',
    'frequency' => '{"type":"simple","details":{"interval":"24","schedule":["08:00"]}}',
    'time' => '08:00:00',
    'start_date' => '2026-02-02',
    'end_date' => '2026-02-10',
    'instructions' => NULL,
    'notes' => NULL,
    'is_active' => 1,
    'registered_by_user_id' => 1,
    'created_at' => '2026-02-02 08:35:44',
    'updated_at' => '2026-02-02 08:35:44',
    'deleted_at' => NULL,
  ),
);

        foreach ($records as $record) {
            DB::table('medications')->updateOrInsert(
                ['id' => $record['id']],
                $record
            );
        }
    }
}
