<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VitalSignsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = array (
  0 => 
  array (
    'id' => 1,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'heart_rate',
    'value' => '[76]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  1 => 
  array (
    'id' => 2,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 130, "diastolic": 90}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  2 => 
  array (
    'id' => 3,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'oxygen_saturation',
    'value' => '[96]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  3 => 
  array (
    'id' => 4,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'blood_glucose',
    'value' => '[140]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  4 => 
  array (
    'id' => 5,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'temperature',
    'value' => '[34]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  5 => 
  array (
    'id' => 6,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:41:51',
    'type' => 'respiratory_rate',
    'value' => '[17]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:41:51',
    'updated_at' => '2026-01-26 02:41:51',
  ),
  6 => 
  array (
    'id' => 7,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 140, "diastolic": 95}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  7 => 
  array (
    'id' => 8,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'heart_rate',
    'value' => '[79]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  8 => 
  array (
    'id' => 9,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'oxygen_saturation',
    'value' => '[100]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  9 => 
  array (
    'id' => 10,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'blood_glucose',
    'value' => '[100]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  10 => 
  array (
    'id' => 11,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'temperature',
    'value' => '[35]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  11 => 
  array (
    'id' => 12,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:42:36',
    'type' => 'respiratory_rate',
    'value' => '[20]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:42:36',
    'updated_at' => '2026-01-26 02:42:36',
  ),
  12 => 
  array (
    'id' => 13,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 160, "diastolic": 90}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  13 => 
  array (
    'id' => 14,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'heart_rate',
    'value' => '[74]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  14 => 
  array (
    'id' => 15,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'blood_glucose',
    'value' => '[140]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  15 => 
  array (
    'id' => 16,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'oxygen_saturation',
    'value' => '[95]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  16 => 
  array (
    'id' => 17,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'temperature',
    'value' => '[35]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  17 => 
  array (
    'id' => 18,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:43:12',
    'type' => 'respiratory_rate',
    'value' => '[18]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:43:12',
    'updated_at' => '2026-01-26 02:43:12',
  ),
  18 => 
  array (
    'id' => 19,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'heart_rate',
    'value' => '[76]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  19 => 
  array (
    'id' => 20,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 140, "diastolic": 60}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  20 => 
  array (
    'id' => 21,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'oxygen_saturation',
    'value' => '[92]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  21 => 
  array (
    'id' => 22,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'blood_glucose',
    'value' => '[135]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  22 => 
  array (
    'id' => 23,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'temperature',
    'value' => '[31]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  23 => 
  array (
    'id' => 24,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:44:11',
    'type' => 'respiratory_rate',
    'value' => '[19]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:44:11',
    'updated_at' => '2026-01-26 02:44:11',
  ),
  24 => 
  array (
    'id' => 25,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 130, "diastolic": 90}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  25 => 
  array (
    'id' => 26,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'heart_rate',
    'value' => '[76]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  26 => 
  array (
    'id' => 27,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'oxygen_saturation',
    'value' => '[90]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  27 => 
  array (
    'id' => 28,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'blood_glucose',
    'value' => '[100]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  28 => 
  array (
    'id' => 29,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'temperature',
    'value' => '[34]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  29 => 
  array (
    'id' => 30,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-26 02:51:11',
    'type' => 'respiratory_rate',
    'value' => '[22]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-26 02:51:11',
    'updated_at' => '2026-01-26 02:51:11',
  ),
  30 => 
  array (
    'id' => 31,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-27 20:00:31',
    'type' => 'heart_rate',
    'value' => '[78]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-27 20:00:31',
    'updated_at' => '2026-01-27 20:00:31',
  ),
  31 => 
  array (
    'id' => 32,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-27 20:00:31',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 160, "diastolic": 140}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-27 20:00:31',
    'updated_at' => '2026-01-27 20:00:31',
  ),
  32 => 
  array (
    'id' => 33,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-27 20:00:31',
    'type' => 'oxygen_saturation',
    'value' => '[99]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-27 20:00:31',
    'updated_at' => '2026-01-27 20:00:31',
  ),
  33 => 
  array (
    'id' => 34,
    'accompanied_person_id' => NULL,
    'group_id' => 2,
    'measured_at' => '2026-01-27 20:00:31',
    'type' => 'blood_glucose',
    'value' => '[110]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-27 20:00:31',
    'updated_at' => '2026-01-27 20:00:31',
  ),
  34 => 
  array (
    'id' => 35,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 120, "diastolic": 90}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  35 => 
  array (
    'id' => 36,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'heart_rate',
    'value' => '[79]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  36 => 
  array (
    'id' => 37,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'oxygen_saturation',
    'value' => '[98]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  37 => 
  array (
    'id' => 38,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'blood_glucose',
    'value' => '[120]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  38 => 
  array (
    'id' => 39,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'temperature',
    'value' => '[35]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  39 => 
  array (
    'id' => 40,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:16:36',
    'type' => 'respiratory_rate',
    'value' => '[20]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:16:36',
    'updated_at' => '2026-01-30 00:16:36',
  ),
  40 => 
  array (
    'id' => 41,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'blood_pressure',
    'value' => '{"systolic": 120, "diastolic": 90}',
    'unit' => 'mmHg',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
  41 => 
  array (
    'id' => 42,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'heart_rate',
    'value' => '[75]',
    'unit' => 'bpm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
  42 => 
  array (
    'id' => 43,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'oxygen_saturation',
    'value' => '[78]',
    'unit' => '%',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
  43 => 
  array (
    'id' => 44,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'blood_glucose',
    'value' => '[110]',
    'unit' => 'mg/dL',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
  44 => 
  array (
    'id' => 45,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'temperature',
    'value' => '[36]',
    'unit' => '°C',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
  45 => 
  array (
    'id' => 46,
    'accompanied_person_id' => NULL,
    'group_id' => 1,
    'measured_at' => '2026-01-30 00:24:08',
    'type' => 'respiratory_rate',
    'value' => '[20]',
    'unit' => 'ipm',
    'systolic_pressure' => NULL,
    'diastolic_pressure' => NULL,
    'heart_rate' => NULL,
    'temperature' => NULL,
    'respiratory_rate' => NULL,
    'oxygen_saturation' => NULL,
    'blood_glucose' => NULL,
    'weight' => NULL,
    'notes' => NULL,
    'recorded_by' => 1,
    'created_at' => '2026-01-30 00:24:08',
    'updated_at' => '2026-01-30 00:24:08',
  ),
);

        foreach ($records as $record) {
            DB::table('vital_signs')->updateOrInsert(
                ['id' => $record['id']],
                $record
            );
        }
    }
}
